version: 2.1
orbs:
  node: circleci/node@5.1.0
  aws-ecr: circleci/aws-ecr@9.0.1
  aws-ecs: circleci/aws-ecs@4.0.0
  aws-cli: circleci/aws-cli@4.1.1

jobs:
  node-app:
    executor:
      name: node/default
      tag: 14.15.1
    steps:
      - checkout
      - run:
          working_directory: ~/project/app/
          command: npm test
          name: Test
workflows:
  devops-teste:
    jobs:
    - node-app
    - aws-ecr/build_and_push_image:
        auth:
          - aws-cli/setup:
              aws_access_key_id: "${AWS_ACCESS_KEY_ID}"
              aws_secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
        repo: "${AWS_RESOURCE_NAME_PREFIX}"
        tag: "${CIRCLE_SHA1}"
        requires:
          - node-app
    - aws-ecs/deploy_service_update:
        auth:
          - aws-cli/setup:
              aws_access_key_id: "${AWS_ACCESS_KEY_ID}"
              aws_secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
        requires:
          - aws-ecr/build_and_push_image # only run this job once aws-ecr/build-and-push-image has completed
        family: "${AWS_RESOURCE_NAME_PREFIX}-service"
        cluster: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
        container_image_name_updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_SHA1}"
